---
title: "Peer-graded Assignment: Course Project: Shiny Application and Reproducible
  Pitch"
author: "Gilbert Tarus"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## **keClimate**  
**Overview**

The dashboard displays the climate change of Kenya from 1991 to 2016. The climatic factors in this context are **Temperature (in degree celsius)** and **Rainfall (mm)**. The application also displays the Summaries of the temperature and rainfall and also the map of Kenya showing the population and the County when you hover the circles.


## **How to Use**
It is a simple application where you can choose the variable to view the plot for from the drop down menu on the sidebar panel. You can also see the averages for the respective variables spanning all years in form of bar plot below the line plot. They are measurements of either temperature in *degree celsius* or rainfall in *mm*.

  * **sidebar panel**: Here, you can choose a variable to view from the drop-down list. The changes are visible on the main panel on select. Also, you can choose a period you want to display the results: ***All the time*** (*default*) shows the results for all years and ***From to Years*** on select displays the slider which you can drag horizontally to choose range of years you want to see the results. The respective changes take place on the **Plot** tab.

## **How to Use Cont'...**  
  * **main panel**: There are three tabs: **Plots, Summaries** and **Map**.  
      - **Plots**: It shows *line plot* and a *barplot*. By default, the plots show line plot and bar plot of monthly averages of temperature in degrees celsius for the all years. You can change this from the `sidebar panel` options.
      - **Summaries**: Shows the summary statistics for all the temperature and rainfall measurements. Below these summaries are two plots showing the `boxplots` of the measurements for all years grouped by Months. You can hover the plots to see some values. 
      - **Map**: Displays the map of Kenya. The Circles, on hover, displays the name of the county and its approximate population. This tab is not associated with the selections on the sidebar panel.

## **Resources**  
The application is running [here](https://tgtarus.shinyapps.io/keClimate/).

The `data` used, `ui.R` and `Server.R` code are in [my github repository](http://demo.com).
